# main repository to fetch from
repo = "helix-editor/helix"
# the repository's branch
remote-branch = "master"
# This is the branch where you will see all result from patchy's work. Set it to any branch you want.
# WARNING: Make sure you do not store any important work on this branch. It will be erased.
local-branch = "patchy"
# List of pull requests which you would like to merge
# TIP: Add comments above pull requests to help yourself understand which PRs do what
pull-requests = [
  # # syntax highlighting for nginx files
  # "12309",
  # adds file explorer
  # "11285",
  # global status line
  "8908",
]
# An optional list of patches to apply, more on them later
patches = []
# main repository to fetch from
# the repository's branch
# This is the branch where you will see all result from patchy's work. Set it to any branch you want.
# WARNING: Make sure you do not store any important work on this branch. It will be erased.
# List of pull requests which you would like to merge
# TIP: Add comments above pull requests to help yourself understand which PRs do what
# An optional list of patches to apply, more on them later
